# [START runtime]
runtime: nodejs10
env: standard
service: realtime
manual_scaling:
  instances: 1
network:
  session_affinity: true
# [END runtime]

# # [START handlers]
# handlers:
#   - url: /(.*\.(css|eot|gz|html|ico|js|json|map|png|svg|ttf|woff|woff2))
#     static_files: build/\1
#     upload: build/(.*\.(css|eot|gz|html|ico|js|json|map|png|svg|ttf|woff|woff2))

#   # Site root, plus anything else, like deep urls
#   # Make this be secure, otherwise oauth redirect won't work if they want to us with http://
#   - url: /.*
#     static_files: build/index.html
#     upload: build/index.html
#     secure: always
#     expiration: '15m'
#   # - url: /
#   #   static_files: build/index.html
#   #   upload: build/index.html
#   # - url: /(.*)
#   #   static_files: build/\1
#   #   upload: build/(.*)
#   # - url: /static
#   #   static_files: build/static/\1
#   #   upload: build/static/(.*)
#   # - url: /service-worker\.js
#   #   static_files: build/service-worker.js
#   #   upload: build/service-worker\.js
#   # - url: /favicon\.ico
#   #   static_files: build/favicon.ico
#   #   upload: build/favicon\.ico
#   # - url: /asset-manifest/.json
#   #   static_files: build/asset-manifest.json
#   #   upload: build/asset-manifest/.json
#   # - url: /manifest/.json
#   #   static_files: build/manifest.json
#   #   upload: build/manifest/.json
#   # - url: /(.*)
#   #   static_files: build/index.html
#   #   upload: build/index.html
# # [END handlers]
